profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns = [
    path('<str:username>/', views.ProfileDetailView.as_view(), name='detail'),
    path('<str:username>/follow/', views.FollowView.as_view(), name='follow'),
    path('<str:username>/profile/', views.UserProfileView.as_view(), name='profile'),
    path('<str:username>/manage/', views.ManageUserView.as_view(), name='manage'),
    path('<int:user_id>/avatar/', views.ManageProfileView.as_view(), name='avatar'),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace = 'feed')),
    path('profile/', include(profiles_urls, namespace = 'profiles')),
    url('', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

#TODO: Delete image file when user is deleted
#TODO: Add functionality to delete user
#TODO: Add functionality to change background image at the profile
#TODO: Move reused code to includes
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,  
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to='profiles', default= 'default/default_avatar.png')

    def __str__(self) -> str:
        return self.user.username

# signal function
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created."""
    if created:
        Profile.objects.create(user=instance)
    
#signal - delete old avatar image file and not default one 
@receiver(models.signals.pre_save, sender=Profile)
def delete_file_on_change(sender, instance, **kwargs):
    if instance.pk:
        try:
            old_image = Profile.objects.get(pk=instance.pk).image
        except Profile.DoesNotExist:
            return
        new_image = instance.image
        if old_image and old_image.url != new_image.url and old_image.url != '/media/default/default_avatar.png':
            old_image.delete(save=False)

profiles/forms.py
from django.contrib.auth.models import User

from django import forms
from .models import Profile


class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

class UserUpdateForm(forms.Form):
    class Meta:
        model = User
        fields = [['username', 'last_name', 'first_name', 'email']]

class ProfileUpdateForm(forms.Form):
    
    class Meta:
        model = Profile
        fields = ['image']

profiles/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.generic import UpdateView, DetailView, View
from django.urls import reverse_lazy



from followers.models import  Follower
from .models import Profile

class ProfileDetailView(DetailView):
    http_method_names = ['get']
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"
    
class FollowView(LoginRequiredMixin, View):
    http_method_names=['post']
    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == 'follow':
            #follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user,
            )
        else:
            #unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None
            
            if follower:
                follower.delete()

 
        return JsonResponse({
            'success':True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

class UserProfileView(DetailView):
    http_method_names = ['get']
    template_name = "profiles/userprofile.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

class ManageUserView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    http_method_names = ['get', 'post']
    template_name = "profiles/manageprofile.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"
    success_url ="../../{username}/profile"
    success_message = "Your Profile has been updated!"
    fields = ['username', 'last_name', 'first_name', 'email']

    if http_method_names == 'POST':

        def dispatch(self, request, *args, **kwargs):
            self.request = request
            return super().dispatch(request, *args, **kwargs)
        
        def form_valid(self, form):
            obj = form.save(commit=False)
            obj.save()
            return super().form_valid(form)

        def get_success_message(self, cleaned_data):
            return self.success_message % dict(
                cleaned_data,
                calculated_field=self.object.calculated_field,
            )

        def get_success_url(self):
            return reverse_lazy('detail', kwargs={"username": self.request.user.username})

class ManageProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    http_method_names = ['get', 'post']
    template_name = "profiles/manageprofiledetails.html"
    model = Profile
    slug_field = "user_id"
    slug_url_kwarg = "user_id"
    success_url ="."
    fields = ['image']
    success_message = "Your Avatar has been updated!"

    if http_method_names == 'POST':
        def dispatch(self, request, *args, **kwargs):
            self.request = request
            return super().dispatch(request, *args, **kwargs)
        
        def form_valid(self, form):
            obj = form.save(commit=False)
            obj.save()
            return super().form_valid(form)

        def get_success_message(self, cleaned_data):
            return self.success_message % dict(
                cleaned_data,
                calculated_field=self.object.calculated_field,
            )

profiles/templates/profiles/detail.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block title %}{{ user.username }}{% endblock title %}

{% block body %}

<!-- component -->
    <div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
        <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
        <div class="flex justify-center -mt-8">
            {% thumbnail user.profile.image "100x100" crop="center" as im %}
                <img class="rounded-full border-solid border-white border-2 -mt-3" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="avatar">
            {% empty %}
                <img class="rounded-full border-solid border-white border-2 mt-3" src="{{user.profile.image.url}}" width="100" height="100" alt="avatar">
            {% endthumbnail %}
        </div>
        <div class="text-center px-3 pb-6 pt-2">
            <h3 class="text-black text-sm bold font-sans">{{ user.username }} </h3>
            
            {% if request.user.is_authenticated %}
                
                {% if  request.user != user %}

                    <div class="my-3">
                        <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center js-follow" data-username="{{ user.username }}" data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}" type="button">
                        <span class="mr-2 js-follow-text">
                            {% if you_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                        </button>
                    </div>
                    
                {% endif %}
                    
            {% else %}
                <div class="mt-3 text-sm">Login to follow this user</div>    
            {% endif %}
                
        </div>
        <div class="flex justify-center pb-3 text-grey-dark">
        <div class="text-center mr-3 border-r pr-3">
            <h2>{{ total_posts }}</h2>
            <span>Posts</span>
        </div>
        <div class="text-center mr-3 border-r pr-3">
            <h2>{{ total_followers }}</h2>
            <span>Followers</span>
        </div>
        <div class="text-center">
            <h2>{{ total_following }}</h2>
            <span>Following</span>
        </div>
        </div>
    </div>

{% endblock body %}

profiles/templates/profiles/manageprofile.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}


{% block title %}{{ user.username }}{% endblock title %}

{% block body %}

    <div class="flex flex-col items-center justify-center min-h-screen bg-gray-100 px-4 py-4">
        <div class="inline-flex bg-white rounded p-2 px-40 shadow-md mb-1 items-center">
            <div class="items-center">
                {% thumbnail request.user.profile.image "100x100" crop="center" as im %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="avatar">
                {% empty %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{user.profile.image.url}}" width="100" height="100" alt="avatar">
                {% endthumbnail %}
                <a href="{% url 'profiles:avatar' request.user.id %}" class="text-xs text-gray-600">Set/Change avatar</a>
            </div>
            <span class="leading-10 text-gray-800 text-4xl font-bold ml-1">{{ request.user.username}}</span>
        <div>
        </div>
        </div>

        <div
        class="rounded-md bg-white w-full max-w-sm sm:max-w-md border border-gray-200 shadow-md px-4 py-4 sm:p-8"
        >
            <div class="text-center sm:text-base text-gray-600 mb-4">Update your profile</div>
        <form class="signup" id="signup_form" method="post" action="{% url 'profiles:manage' request.user.username %}" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="flex flex-col mb-4">
                    <label for="name" class="mb-1 text-xs sm:text-sm tracking-wide text-gray-600">Username:</label>
                    <div class="relative">
                        <div
                            class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400"
                            >
                            <svg
                                class="h-6 w-6"
                                fill="none"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </div>

                        {% render_field form.username|append_attr:"class:text-sm sm:text-base placeholder-gray-500 pl-10 pr-4 rounded-lg border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" type="text" placeholder="Enter a username" %}
                    </div>
                </div>

                <div class="flex flex-col mb-4">
                    <label for="name" class="mb-1 text-xs sm:text-sm tracking-wide text-gray-600">Last name:</label>
                    <div class="relative">
                        <div
                            class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400"
                            >
                            <svg
                                class="h-6 w-6"
                                fill="none"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </div>

                        {% render_field form.last_name|append_attr:"class:text-sm sm:text-base placeholder-gray-500 pl-10 pr-4 rounded-lg border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" type="text" placeholder="Enter a username" %}
                    </div>
                </div>

                <div class="flex flex-col mb-4">
                    <label for="name" class="mb-1 text-xs sm:text-sm tracking-wide text-gray-600">First name:</label>
                    <div class="relative">
                        <div
                            class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400"
                            >
                            <svg
                                class="h-6 w-6"
                                fill="none"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </div>

                        {% render_field form.first_name|append_attr:"class:text-sm sm:text-base placeholder-gray-500 pl-10 pr-4 rounded-lg border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" type="text" placeholder="Enter a username" %}
                    </div>
                </div>

                <div class="flex flex-col mb-4">
                    <label
                        for="email"
                        class="mb-1 text-xs sm:text-sm tracking-wide text-gray-600"
                    >E-Mail Address:</label>
                    <div class="relative">
                        <div
                        class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400"
                        >
                            <svg
                                class="h-6 w-6"
                                fill="none"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path
                                d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207"
                                />
                            </svg>
                        </div>

                        {% render_field form.email|append_attr:"class:text-sm sm:text-base placeholder-gray-500 pl-10 pr-4 rounded-lg border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400" type="email" placeholder="Enter your e-mail" %}
                    </div>
                </div>

                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                <div class="flex w-full mt-6">
                <button
                    type="submit"
                    class="flex items-center justify-center focus:outline-none text-white text-sm sm:text-base bg-indigo-600 hover:bg-indigo-700 rounded py-2 w-full transition duration-150 ease-in"
                >
                    <span class="mr-2 uppercase">Update my profile</span>
                </button>
                </div>
        </form>

            <div class="flex justify-center items-center mt-6">
            <a
                href="{% url 'account_change_password' %}"
                class="inline-flex items-center font-bold text-indigo-500 hover:text-indigo-700 text-sm text-center"
            >
                <span class="ml-2">Click here to change your password &nbsp</span>
                <span>
                    <svg
                        class="h-6 w-6"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                    >
                        <path
                        d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"
                        />
                    </svg>
                </span>
            </a>
            </div>
        </div>
        
    </div>

{% endblock body %}

profiles/templates/profiles/manageprofiledetails.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load widget_tweaks %}
{% load i18n %}


{% block body %}

    <!-- component -->
    <div class="flex flex-col items-center justify-center min-h-screen bg-gray-100 px-4 py-8">
        <div class="inline-flex bg-white rounded p-2 px-40 shadow-md mb-1 items-center">
            <div class="items-center">
                {% thumbnail request.user.profile.image "100x100" crop="center" as im %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="avatar">
                {% empty %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{user.profile.image.url}}" width="100" height="100" alt="avatar">
                {% endthumbnail %}
            </div>
            <span class="leading-10 text-gray-800 text-4xl font-bold ml-1">{{ request.user.username}}</span>
        <div>
    </div>
    </div>


    <div
      class="rounded-md bg-white w-full max-w-sm sm:max-w-md border border-gray-200 shadow-md px-4 py-6 sm:p-8"
    >
    <div class="text-lg text-gray-600 my-4">Choose a new Avatar.</div>
        <form method="post" action="{% url 'profiles:avatar' request.user.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="flex flex-col mb-6">
                <label
                    for="email"
                    class="mb-1 text-xs sm:text-sm tracking-wide text-gray-600"
                ></label>
                <div class="relative">
                    <div
                        class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400"
                        >
                        <svg class="h-9 w-9"
                            fill="none"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            viewBox="0 0 24 24"
                            stroke="currentColor">
							<path fill="none" d="M19.521,7.267c-0.144-0.204-0.38-0.328-0.631-0.328h-3.582l-0.272-1.826c-0.055-0.379-0.379-0.656-0.76-0.656
							H9.802l-0.39-0.891c-0.123-0.279-0.399-0.46-0.704-0.46H1.11c-0.222,0-0.434,0.096-0.58,0.264C0.385,3.537,0.319,3.76,0.349,3.981
							l1.673,12.243c0,0,0,0,0,0.002v0.004c0.015,0.113,0.06,0.213,0.119,0.303c0.006,0.009,0.006,0.023,0.012,0.033
							c0.012,0.016,0.033,0.024,0.046,0.04c0.054,0.065,0.114,0.118,0.185,0.161c0.027,0.018,0.051,0.035,0.078,0.048
							c0.099,0.045,0.206,0.078,0.32,0.078h0.002l0,0h13.03c0.323,0,0.611-0.201,0.722-0.505l3.076-8.416
							C19.698,7.735,19.663,7.474,19.521,7.267z M8.203,4.644l0.391,0.889c0.123,0.279,0.399,0.461,0.704,0.461h4.315l0.141,0.944H5.859
							c-0.323,0-0.611,0.201-0.723,0.505l-2.011,5.505L1.992,4.644H8.203z M15.276,15.356H3.882l2.515-6.879H17.79L15.276,15.356z"></path>
						</svg>
                    </div>
                    <div class="text-sm sm:text-base placeholder-gray-500 pl-10 pr-4 rounded-lg border border-gray-400 w-full py-2 focus:outline-none focus:border-blue-400">
                        {{ form.image }}
                    </div>
                </div>
            </div>

            <div class="flex w-full">
                <button
                    type="submit"
                    class="flex items-center justify-center focus:outline-none text-white text-sm sm:text-base bg-indigo-600 hover:bg-indigo-700 rounded py-2 w-full transition duration-150 ease-in"
                    >
                    <span class="mr-2 uppercase">Update my Avatar</span>
                    <span>
                        <svg
                            class="h-6 w-6"
                            fill="none"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                            >
                            <path d="M13 9l3 3m0 0l-3 3m3-3H8m13 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </span>
                </button>
            </div>
        </form>
    </div>
  </div>


{% endblock body %}

profiles/templates/profiles/userprofile.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block title %}{{ user.username }}{% endblock title %}

{% block body %}


<!-- component -->
<div class="my-10">
    <div class="bg-white rounded overflow-hidden shadow-lg">
        <div class="text-center p-6  border-b">
            <div class="flex justify-center">
                {% thumbnail request.user.profile.image "100x100" crop="center" as img %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}" alt="avatar">
                {% empty %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{user.profile.image.url}}" width="100" height="100" alt="avatar">
                {% endthumbnail %}
            </div>
            <p class="pt-2 text-lg font-semibold">{{ request.user.username }}</p>
            <div class="flex justify-center py-3 text-grey-dark">
                <div class="text-center mr-3 border-r pr-3">
                    <h2>{{ total_posts }}</h2>
                    <span>Posts</span>
                </div>
                <div class="text-center mr-3 border-r pr-3">
                    <h2>{{ total_followers }}</h2>
                    <span>Followers</span>
                </div>
                <div class="text-center">
                    <h2>{{ total_following }}</h2>
                    <span>Following</span>
                </div>
            </div>
        </div>
        <div class="border-b">
            <a href="#" class="px-4 py-2 hover:bg-gray-100 flex">
                <div class="text-gray-800">
                    <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    class="w-5 h-5"
                    >
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                    </svg>
                    
                </div>
                <div class="pl-3">
                    <p class="text-sm font-medium text-gray-800 leading-none pb-2">Last Name: {{ request.user.last_name }}</p>
                    <p class="text-sm font-medium text-gray-800 leading-none">Name: {{ request.user.first_name }}</p>
                </div>
            </a>
            <a href="#" class="px-4 py-2 hover:bg-gray-100 flex">
                <div class="text-gray-800">
                    <span class="flex items-center justify-center text-lg text-gray-800">
                        <svg 
                            class="w-5 h-5" 
                            fill="none" 
                            stroke="currentColor" 
                            viewBox="0 0 24 24" 
                            stroke-linecap="round" 
                            stroke-linejoin="round" 
                            stroke-width="2"
                            >
                            <path  d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"></path>
                        </svg>
                    </span>
                </div>
                <div class="pl-3">
                    <p class="text-sm font-medium text-gray-800 leading-none">E-mail</p>
                    <p class="text-xs text-gray-500">{{ request.user.email}}</p>
                </div>
            </a>
            <a href="#" class="px-4 py-2 hover:bg-gray-100 flex">
                <div class="text-gray-800">
                    <svg
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        class="h-5 w-5"
                        >
                            <path
                            d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"
                            />
                    </svg>
                </div>
                <div class="pl-3">
                    <p class="text-sm font-medium text-gray-800 leading-none">Date joined</p>
                    <p class="text-xs text-gray-500">{{ request.user.date_joined }}</p>
                </div>
            </a>
            <a href="#" class="px-4 py-2 hover:bg-gray-100 flex">
                <div class="text-gray-800">
                    <svg
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        class="h-5 w-5"
                        >
                        <path
                            d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z"
                        />
                    </svg>
                </div>
                <div class="pl-3">
                    <p class="text-sm font-medium text-gray-800 leading-none">Last login</p>
                    <p class="text-xs text-gray-500">{{ request.user.last_login }}</p>
                </div>
            </a>
        </div>
    </div>
    <div class="mt-5 text-center">
        <a
            href="{% url 'profiles:manage' user.username %}"
            class="border rounded-full py-2 px-4 text-xs font-semibold text-gray-700 hover:bg-gray-100"
        >
            Manage your Account
        </a>
    </div>
</div>

{% endblock body %}