feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('new/', views.CreateNewPost.as_view(), name='new_post'),
    path('myposts/', views.UserPosts.as_view(), name='user_posts'),
    path('followedby/', views.FollowedByPosts.as_view(), name='followedby_posts'),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace = 'feed')),
    path('profile/', include(profiles_urls, namespace = 'profiles')),
    url('', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

til/templates/includes/messages.html
<div>
    {% if messages %}
        {% for message in messages %}
            
            {% if message.tags == 'info' %}
                {% include 'includes/messages/info.html' %}
            {% elif message.tags == 'success' %}
                {% include 'includes/messages/success.html' %}
            {% elif message.tags == 'warning' %}
                {% include 'includes/messages/warning.html' %}
            {% elif message.extra_tags == 'TILpost' %}
                {% include 'includes/messages/success.html' %}
            {% else %}
                {% include 'includes/messages/danger.html' %}
            {% endif %}
                
        {% endfor %}
    {% endif %}
</div>

til/templates/includes/post.html
{% load thumbnail %}

<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 50rem'>
    
    {% if messages %}
        {% for message in messages %}
            {% if message.extra_tags == 'TILpost' %}
                {% include 'includes/messages.html' %}
            {% endif %}
         {% endfor %}            
    {% endif %}
        
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{ post.date|date:"F j Y, g:i:a" }}</span>
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">{{ post.text }}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        
        {% if show_detail_link %}
            <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
                Read more
            </a>
        {% else %}
            <span>&nbsp;</span>
        {% endif %}
            
        <div>
            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "100x100" crop="center" as im %}
                    <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="avatar">
                {% empty %}
                    <img class="rounded-full border-solid border-white border-2 mt-3" src="{{user.profile.image.url}}" width="100" height="100" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{ post.author.username }}</h1>
            </a>
        </div>
    </div>
</div>